### PR TITLE
Update modules

### PR DESCRIPTION
**Pull request by cgiraldo**
Use k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1 instead of k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1.

Use sirupsen/logrus instead of Sirupsen/logrus https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

### CODE REVIEW

**Comment by yuzhang66** [comment]
Hi Cgiraldo, Thank you for your contribution! Considering there's a lot library updates, I need to testing this pull request in our internal testing repo and going through the open-source legal scanning process, so currently I'm not able to directly merge your pull request, I will add your name & github account in an contribution list in our next release to prove your contribution, is this ok for you?

**Comment by cgiraldo** [comment]
It is Ok.

**Comment by cgiraldo** [comment]
i have also include a commit to support zcu102 board. Thanks to @Vae1997 and the repo: https://github.com/Vae1997/zcu102-fpga-device-plugin-demo

**Comment by cgiraldo** [comment]
Github repo was transfered to Gradiant Organization:
https://github.com/Gradiant/SI-PR-01370-FPGA_as_a_Service

**Pull request closed without merging**
